version: '3'

tasks:
  build:
    cmds:
      - source .env && go build -v ./...

  test:
    cmds:
      - source .env && go test -v ./...

  lint:
    cmds:
      - golangci-lint run

  run:
    cmds:
      - source .env && docker-compose up --build

