version: '3'

tasks:
  build:
    cmds:
      - go build -v ./...

  test:
    cmds:
      - go test -v ./...

  lint:
    cmds:
      - golangci-lint run

  run:
    cmds:
      - export CLOUDSDK_AUTH_ACCESS_TOKEN=$(gcloud auth print-access-token) && docker-compose up --build

  deploy:
    cmds:
      - |
        gcloud run deploy user-api \
        --source . \
        --project $PROJECT_ID \
        --port 8080 \
        --service-account $SERVICE_ACCOUNT \
        --region asia-southeast1 \
        --set-env-vars PROJECT_ID=$PROJECT_ID \
        --update-secrets=ECDSA_PRIVATE_KEY=ECDSAPrivateKey:latest,ECDSA_PUBLIC_KEY=ECDSAPublicKey:latest