version: '3'

tasks:
  build:
    cmds:
      - mkdir -p build
      - source .env && CGO_ENABLED=0 GOOS=linux go build -a -o build/app ./cmd/server

  test:
    cmds:
      - source .env && go test -v ./tests/...

  lint:
    cmds:
      - golangci-lint run

  run:
    cmds:
      - source .env && docker-compose up --build

